version: "3.8"

services:
  postgresql:
    image: postgres:alpine
    container_name: postgres_test
    environment:
      - POSTGRES_PASSWORD=contrasena
      - POSTGRES_DB=test
    expose:
      - '5432'
    networks:
      - mynetwork
  block10-dockerize-app:
    image: block10-dockerize-app
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
networks:
  mynetwork:
    driver: bridge